### ISSUE TITLE
HTTP 103 - Early Hints 

### ISSUE THREAD

**Issue by mesaugat** [prettymuchbryce/http-status-codes#20]
Looks like this new HTTP status code has been approved. https://datatracker.ietf.org/doc/draft-ietf-httpbis-early-hints/

Discussion here: https://news.ycombinator.com/item?id=15590049

But it doesn't seem to have a dedicated RFC page right now. I think it makes sense to add it to the list of status codes later.

**Comment by prettymuchbryce** [comment]
Agreed. Lets keep an eye on it and plan to add it in later.

**Comment by seanmhanson** [comment]
This got an experimental RFC in Dec 2017, and is still in that state. Since it's in usage experimentally, would it make sense to surface it here?

Here's the [RFC page](https://tools.ietf.org/html/rfc8297) and, if you're curious, the [RFC editor page](https://www.rfc-editor.org/info/rfc8297) for feedback.

**Comment by prettymuchbryce** [comment]
Thanks for those links Sean. This seems pretty useful to me, although I'm not sure how prevalent it is in the wild right now.

I would happily accept a PR for this status code.

**Comment by pgcalixto** [comment]
Hey guys, it seems that @seanmhanson added 103 HTTP status code on https://github.com/prettymuchbryce/http-status-codes/pull/43.

It seems that https://github.com/prettymuchbryce/http-status-codes/pull/43 was closed due to its logic being included on https://github.com/prettymuchbryce/http-status-codes/pull/49.
However, https://github.com/prettymuchbryce/http-status-codes/pull/49 did not include 103.

I'd be happy to include 103 code but @seanmhanson did all the work already.
How are we on this?

**Comment by angellee177** [comment]
@prettymuchbryce please kindly review this PR [https://github.com/prettymuchbryce/http-status-codes/pull/89](url). :)
